using System.Text;

namespace NML.Core.Launch;

/// <summary>
/// Serializes a resolved launch command (java executable + JVM/game args) into a runnable
/// <c>.bat</c> (Windows) or <c>.sh</c> (Unix) script — HMCL's "导出启动脚本" feature. The exported
/// script launches the game without the launcher, which is useful for debugging, shortcuts, or
/// running on another machine with the same game directory.
/// </summary>
public static class LaunchScriptExporter
{
    /// <summary>
    /// Build the script text. <paramref name="shell"/> selects the flavor: "bat" produces a
    /// Windows batch file, anything else produces a POSIX sh script.
    /// </summary>
    public static string BuildScript(string javaExecutable, IReadOnlyList<string> args,
        string workingDirectory, string shell = "bat")
    {
        if (string.IsNullOrWhiteSpace(javaExecutable))
            throw new ArgumentException("Java executable is required.", nameof(javaExecutable));
        if (args is null || args.Count == 0)
            throw new ArgumentException("At least one launch argument is required.", nameof(args));

        bool isBat = string.Equals(shell, "bat", StringComparison.OrdinalIgnoreCase);
        var sb = new StringBuilder();

        if (isBat)
        {
            sb.AppendLine("@echo off");
            sb.AppendLine("rem Generated by NextMinecraftLauncher — launches Minecraft without the launcher.");
            sb.AppendLine($"cd /d \"{workingDirectory}\"");
            sb.AppendLine($"{QuoteBat(javaExecutable)} {string.Join(" ", args.Select(QuoteBat))}");
            sb.AppendLine("pause");
        }
        else
        {
            sb.AppendLine("#!/bin/sh");
            sb.AppendLine("# Generated by NextMinecraftLauncher — launches Minecraft without the launcher.");
            sb.AppendLine($"cd \"{workingDirectory.Replace("\"", "\\\"")}\"");
            sb.AppendLine($"{QuoteSh(javaExecutable)} {string.Join(" ", args.Select(QuoteSh))}");
        }
        return sb.ToString();
    }

    /// <summary>Write the script to <paramref name="path"/> (creates parent dirs; chmod +x on Unix).</summary>
    public static void Export(string javaExecutable, IReadOnlyList<string> args,
        string workingDirectory, string path)
    {
        bool isBat = path.EndsWith(".bat", StringComparison.OrdinalIgnoreCase);
        string script = BuildScript(javaExecutable, args, workingDirectory, isBat ? "bat" : "sh");
        string? dir = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(path, script, new UTF8Encoding(false));

        // Make .sh executable on Unix.
        if (!isBat && !OperatingSystem.IsWindows())
        {
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("chmod", $" +x \"{path}\""));
            }
            catch { /* best-effort; the user can chmod manually */ }
        }
    }

    /// <summary>Quote a value for cmd.exe: only when it contains spaces, wrapping in double quotes.</summary>
    private static string QuoteBat(string s)
    {
        if (string.IsNullOrEmpty(s)) return "\"\"";
        // cmd quoting: wrap in quotes when the value has spaces; escape inner quotes by doubling.
        if (s.Contains(' ') || s.Contains('"'))
            return "\"" + s.Replace("\"", "\"\"") + "\"";
        return s;
    }

    /// <summary>POSIX single-quote: wrap and escape any inner single quotes as '\'\'.</summary>
    private static string QuoteSh(string s)
    {
        if (string.IsNullOrEmpty(s)) return "''";
        return "'" + s.Replace("'", "'\\''") + "'";
    }
}
